name: Adapter submission
description: Submit a community adapter to be considered for the curated list in @apihive/core documentation.
title: "Adapter: <DescriptiveName>"
labels:
  - type:adapter-submission
  - status:pending
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing an adapter! Please fill out the fields below.
  - type: input
    id: githubRepo
    attributes:
      label: githubRepo
      description: Link to the adapter's GitHub repository (public).
      placeholder: https://github.com/owner/repo
    validations:
      required: true
  - type: input
    id: descriptiveName
    attributes:
      label: descriptiveName
      description: Human-friendly name for the adapter.
      placeholder: Auditor
    validations:
      required: true
  - type: textarea
    id: shortDescription
    attributes:
      label: shortDescription
      description: One- or two-sentence description.
      placeholder: Adds auditing capabilities to APIHive requests with service X.
    validations:
      required: true
